#!/bin/sh

REM="$(seq -s' ' 0 99)"

python task_data_removal.py --config ntk_prompt --seed 2024 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2024 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2024 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2024 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2024 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2024 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2024 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2024 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM

python task_data_removal.py --config ntk_prompt --seed 2025 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2025 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2025 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2025 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2025 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2025 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2025 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2025 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM

python task_data_removal.py --config ntk_prompt --seed 2026 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2026 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2026 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2026 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2026 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2026 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2026 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_data_removal.py --config ntk_prompt --seed 2026 --dataset_name mnli --num_train_dp 5000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
