#!/bin/sh
# python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 32 --lr 1e-4
python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 32 --lr 2e-4
python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 32 --lr 3e-4
python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 32 --lr 4e-4
python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 32 --lr 5e-4
python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 32 --lr 1e-3
# python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 16 --lr 5e-5
# python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 16 --lr 1e-4
# python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 16 --lr 2e-4
# python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 16 --lr 3e-4
# python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 16 --lr 4e-4
python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 16 --lr 5e-4
python prompt_finetune_train.py --dataset_name mnli --num_train_dp 1000 --tmc_iter 500 --approximate inv --lambda_ 1e-6  --sweep_mode percentage --sweep_start 1 --sweep_end 100 --sweep_step 1 --batch_size 16 --lr 1e-3