#!/bin/sh

REM="$(seq -s' ' 0 99)"

python task_shapley.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500

python task_shapley.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500

python task_shapley.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 1000 --approximate inv --inv_lambda_ 1e-6 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 1 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 5 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 10 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 15 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 20 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 25 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name mnli --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name mnli --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 1000 --approximate eigen --eigen_rank 30 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500

python task_shapley.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2024 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2024 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500

python task_shapley.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2025 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2025 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500

python task_shapley.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 872 --approximate inv --inv_lambda_ 1e-6 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 1 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 5 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 10 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 15 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 20 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 25 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
python task_shapley.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_selection.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500
python task_data_removal.py --config ntk_llama --seed 2026 --dataset_name sst2 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --inv_lambda_ 1e-6 --eigen_lambda_ 1e-2 --eigeps 1e-8 --tmc_iter 500 --num_train_removed_list $REM
python task_wrong_label_detection.py --dataset_name sst2 --config ntk_llama --seed 2026 --num_train_dp 2000 --val_sample_num 872 --approximate eigen --eigen_rank 30 --eigen_lambda_ 1e-2 --eigeps 1e-8 --poison_pct 10 --tmc_iter 500
