import pickle
import numpy as np
import yaml
import torch
import random
from datasets import load_dataset
import time

import sys, os
sys.path.insert(0, './lmntk')
sys.path.insert(0, './vinfo/lmntk')

from dataset import *
from probe import *
from dvutils.Data_Shapley import Fast_Data_Shapley  # YAML tag 해석용

import argparse


def log_gpu_info():
    cuda_visible = os.environ.get("CUDA_VISIBLE_DEVICES")
    print(f"[gpu] CUDA_VISIBLE_DEVICES={cuda_visible}")
    print(f"[gpu] torch.cuda.is_available()={torch.cuda.is_available()}")

    if not torch.cuda.is_available():
        print("[gpu] CUDA is not available. Running on CPU.")
        return

    device_count = torch.cuda.device_count()
    print(f"[gpu] torch.cuda.device_count()={device_count}")

    for gpu_idx in range(device_count):
        props = torch.cuda.get_device_properties(gpu_idx)
        total_mem_gb = props.total_memory / (1024 ** 3)
        print(
            f"[gpu] cuda:{gpu_idx} name={props.name}, total_memory={total_mem_gb:.2f} GB"
        )

    current_idx = torch.cuda.current_device()
    print(f"[gpu] torch.cuda.current_device()={current_idx}")
    print(f"[gpu] current_device_name={torch.cuda.get_device_name(current_idx)}")


def get_gpu_info():
    """Collect GPU information for timing records"""
    gpu_info = {}
    
    if not torch.cuda.is_available():
        gpu_info['device_type'] = 'CPU'
        gpu_info['used_gpu_count'] = 0
        return gpu_info
    
    cuda_visible = os.environ.get("CUDA_VISIBLE_DEVICES")
    current_idx = torch.cuda.current_device()
    current_device_name = torch.cuda.get_device_name(current_idx)
    
    gpu_info['used_gpu_count'] = 1  # Single GPU usage (no DataParallel)
    gpu_info['gpu_index'] = f"cuda:{current_idx}"
    gpu_info['gpu_model'] = current_device_name
    if cuda_visible:
        gpu_info['cuda_visible_devices'] = cuda_visible
    
    return gpu_info


# Full train set sizes for reproducing poison indices (from HuggingFace datasets)
DATASET_FULL_TRAIN_SIZE = {
    "sst2": 67349,
    "mr": 8530,
    "subj": 8000,
    "ag_news": 120000,
    "rte": 2490,
    "mnli": 392702,
    "mrpc": 3668,
    "qqp": 363846,
}


def get_poison_indices(dataset_name, poison_pct, poison_seed=2025):
    """
    Reproduce the exact poison indices generated by dataset.py's EasyReader.
    dataset.py uses random.seed(2025) and random.sample(range(nrows), num_to_flip)
    where nrows is the full train set size.
    """
    if dataset_name not in DATASET_FULL_TRAIN_SIZE:
        raise ValueError(f"Unknown dataset: {dataset_name}. "
                         f"Supported: {list(DATASET_FULL_TRAIN_SIZE.keys())}")
    
    nrows = DATASET_FULL_TRAIN_SIZE[dataset_name]
    num_to_flip = int(nrows * poison_pct / 100)
    
    rng = random.Random(poison_seed)
    indices_to_flip = set(rng.sample(range(nrows), num_to_flip))
    
    return indices_to_flip, nrows, num_to_flip


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset_name", type=str, default="mr")
    parser.add_argument("--seed", type=int, default=2025)
    parser.add_argument("--num_train_dp", type=int, default=8530)
    parser.add_argument("--val_sample_num", type=int, default=1066)
    parser.add_argument("--tmc_iter", type=int, default=500)
    parser.add_argument("--approximate", type=str, default="inv",
                        choices=["inv", "eigen", "none"])
    parser.add_argument("--eigen_rank", type=int, default=30,
                        help="Eigen rank as percentage of num_train_dp (e.g., 10 means 10%% of data)")
    parser.add_argument("--inv_lambda_", type=float, default=1e-6,
                        help="Lambda (regularization parameter) for INV mode")
    parser.add_argument("--eigen_lambda_", type=float, default=1e-2,
                        help="Lambda (regularization parameter) for Eigen mode")
    parser.add_argument("--poison_pct", type=int, default=10,
                        help="Percentage of training labels to flip (e.g., 10 means 10%%)")
    parser.add_argument("--poison_seed", type=int, default=2025,
                        help="Random seed for poison index generation (must match dataset.py)")
    parser.add_argument("--num_train_selected_list", type=int, nargs='+',
                        default=[i for i in range(1, 101)],
                        help="List of percentages (1-100) to inspect from lowest Shapley")
    parser.add_argument("--log_early_stopping", action="store_true",
                        help="Enable logging of early stopping points in TMC iterations")
    return parser.parse_args()


def main():
    args = parse_args()
    log_gpu_info()

    dataset_name = args.dataset_name
    seed = args.seed
    num_train_dp = args.num_train_dp
    val_sample_num = args.val_sample_num

    tmc_iter = args.tmc_iter
    approximate = args.approximate
    num_train_selected_list = args.num_train_selected_list
    eigen_rank_pct = args.eigen_rank
    inv_lambda_ = args.inv_lambda_
    eigen_lambda_ = args.eigen_lambda_
    log_early_stopping = args.log_early_stopping
    poison_pct = args.poison_pct
    poison_seed = args.poison_seed

    # Initialize timing info dictionary
    timing_info = {}
    
    # Collect GPU information
    gpu_info = get_gpu_info()
    timing_info['gpu_info'] = gpu_info

    # Calculate actual eigen rank from percentage
    eigen_rank = int(num_train_dp * eigen_rank_pct / 100)
    print(f"[info] eigen_rank={eigen_rank_pct}% of num_dp={num_train_dp} -> actual rank={eigen_rank}")

    prompt = True
    signgd = False

    # eigen 파라미터
    eigen_solver = "cholesky"
    eigen_dtype = "float32"

    per_point = True
    early_stopping = "True"

    # Dynamic path construction based on dataset_name
    # Use poison YAML config (data_poison: True)
    yaml_path = f"../configs/dshap/{dataset_name}/ntk_prompt_posion.yaml"
    base_path = f"./freeshap_res/{dataset_name}"
    detection_base_path = f"./freeshap_res/wrong_label_detection/{dataset_name}"

    # seed 고정 (재현성 보장)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    np.random.seed(seed)
    random.seed(seed)

    # ===== YAML 로드 =====
    yaml_args = yaml.load(open(yaml_path), Loader=yaml.Loader)
    list_dataset = yaml_args["dataset"]
    probe_model = yaml_args["probe_com"]
    dshap_com = yaml_args["dshap_com"]

    # Enable early stopping logging if requested
    if log_early_stopping:
        dshap_com.log_early_stopping = True
        print(f"[info] Early stopping logging enabled")

    if prompt:
        probe_model.model.init(list_dataset.label_word_list)

    if approximate != "none":
        probe_model.approximate(approximate)

    if approximate == "eigen":
        probe_model.set_eigen_params(
            rank=eigen_rank,
            lam=eigen_lambda_,
            solver=eigen_solver,
            dtype=eigen_dtype,
            seed=seed
        )
    elif approximate == "inv":
        probe_model.set_inv_params(lam=inv_lambda_)

    if signgd:
        probe_model.signgd()

    # ===== model_name 결정 =====
    if 'llama' in probe_model.args['model']:
        model_name = 'llama'
    elif 'roberta' in probe_model.args['model']:
        model_name = 'roberta'
    elif 'bert' in probe_model.args['model']:
        model_name = 'bert'
    else:
        model_name = 'model'

    # ===== 1) NTK 캐시 로드 (indices도 같이 로드) =====
    # NTK는 라벨과 무관하므로 기존 캐시 그대로 사용
    ntk_path = (
        f"{base_path}/ntk/{model_name}"
        f"_seed{seed}_num{num_train_dp}_val{val_sample_num}_sign{signgd}.pkl"
    )
    print(f"[info] ntk_path = {ntk_path}")

    with open(ntk_path, "rb") as f:
        bundle = pickle.load(f)

    if not (isinstance(bundle, dict) and "ntk" in bundle):
        raise RuntimeError(
            "NTK cache format is old (ntk only). "
            "Please regenerate NTK with the updated script that stores indices."
        )

    ntk = bundle["ntk"]
    sampled_idx = np.array(bundle["sampled_idx"])
    sampled_val_idx = np.array(bundle["sampled_val_idx"])
    print(f"[info] loaded NTK + indices: |train|={len(sampled_idx)}, |val|={len(sampled_val_idx)}")

    # probe에 NTK 주입
    probe_model.get_cached_ntk(ntk)

    # ===== 2) train/val set 구성 (poison된 라벨이 반영됨) =====
    train_set = list_dataset.get_idx_dataset(sampled_idx, split="train")
    val_set = list_dataset.get_idx_dataset(sampled_val_idx, split="val")
    probe_model.get_train_labels(train_set)

    # eigen이면 feature 준비
    if approximate == "eigen":
        print("[info] Preparing eigen regression features...")
        import time as time_module
        eigen_start_time = time_module.time()
        probe_model.prepare_eigen_regression()
        eigen_total_time = time_module.time() - eigen_start_time
        
        if hasattr(probe_model, 'eigen_regression') and probe_model.eigen_regression is not None:
            eigendecom_time = probe_model.eigen_regression.eigen_decomposition_time
            timing_info['eigendecomposition'] = eigendecom_time
            timing_info['eigen_preparation_total'] = eigen_total_time
            timing_info['eigen_preparation_overhead'] = eigen_total_time - eigendecom_time
            print(f"[TIMING] Eigendecomposition time: {eigendecom_time:.4f}s")
            print(f"[TIMING] Total eigen preparation time: {eigen_total_time:.4f}s")
            print(f"[TIMING] Overhead (non-decomposition): {eigen_total_time - eigendecom_time:.4f}s")

    print("len(train_set) =", len(train_set))
    print("len(val_set)   =", len(val_set))

    # ===== 3) Shapley 결과 경로 (poison 태그 포함) =====
    method_dir = approximate

    if approximate == "eigen":
        lambda_str = f"{eigen_lambda_:.0e}"
        extra_tag = f"_eig{eigen_rank_pct}_lam{lambda_str}_{eigen_solver}_{eigen_dtype}"
    else:
        lambda_str = f"{inv_lambda_:.0e}"
        extra_tag = f"_lam{lambda_str}"

    poison_tag = f"_poison{poison_pct}"

    shapley_path = (
        f"{detection_base_path}/shapley/{method_dir}/results/{model_name}"
        f"_seed{seed}_num{num_train_dp}_val{val_sample_num}"
        f"{extra_tag}_sign{signgd}_earlystop{early_stopping}"
        f"_tmc{tmc_iter}{poison_tag}.pkl"
    )
    print(f"[info] shapley_path = {shapley_path}")

    # Setup early stopping log file if enabled
    if log_early_stopping:
        setting_name = os.path.basename(shapley_path).replace('.pkl', '')
        early_stop_dir = f"{detection_base_path}/shapley/{method_dir}/early_stopping"
        os.makedirs(early_stop_dir, exist_ok=True)
        early_stop_path = f"{early_stop_dir}/{setting_name}.txt"
        
        k_width = len(str(num_train_dp))
        n_width = len(str(num_train_dp))
        with open(early_stop_path, 'a') as f:
            f.write(f"TMC Iteration Log\n")
            f.write(f"{'='*60}\n")
            f.write(f"Dataset: {dataset_name}, Train: {num_train_dp}, Val: {val_sample_num}\n")
            f.write(f"Mode: {approximate}, TMC iterations: {tmc_iter}, Seed: {seed}\n")
            f.write(f"Poison: {poison_pct}%\n")
            f.write(f"Early stopping enabled: {early_stopping}\n")
            f.write(f"\n{'Iter':<6} {'k':>{k_width}} / {'n':<{n_width}} {'Pct':>7} {'Status':<12}\n")
            f.write(f"{'-'*6} {'-'*k_width}   {'-'*n_width} {'-'*7} {'-'*12}\n")
        
        dshap_com.early_stopping_log_path = early_stop_path
        dshap_com._log_k_width = k_width
        dshap_com._log_n_width = n_width
        dshap_com._log_iter = 0
        print(f"[info] Early stopping log will be written to: {early_stop_path}")

    # ===== 4) Shapley 로드 or 계산 =====
    shapley_computation_time = None
    try:
        with open(shapley_path, "rb") as f:
            result = pickle.load(f)
        print(f"[info] loaded Shapley from {shapley_path}")

        dv_result = result["dv_result"]
        if "sampled_idx" in result:
            sampled_idx = np.array(result["sampled_idx"])
        if "sampled_val_idx" in result:
            sampled_val_idx = np.array(result["sampled_val_idx"])

        if "timing_info" in result:
            timing_info = result["timing_info"]
            print(f"[info] loaded timing info from cache: {timing_info}")

    except Exception as e:
        print("[info] shapley cache miss -> computing Shapley (with poisoned labels)")
        print(f"[info] reason: {e}")

        shapley_start_time = time.time()

        dv_result = dshap_com.run(
            data_idx=sampled_idx.tolist(),
            val_data_idx=sampled_val_idx.tolist(),
            iteration=tmc_iter,
            use_cache_ntk=True,
            prompt=prompt,
            seed=seed,
            num_dp=num_train_dp,
            checkpoint=False,
            per_point=per_point,
            early_stopping=early_stopping
        )

        shapley_computation_time = time.time() - shapley_start_time
        timing_info['shapley_computation'] = shapley_computation_time
        print(f"[TIMING] Shapley computation time: {shapley_computation_time:.4f}s")

        result = {
            "dv_result": dv_result,
            "sampled_idx": sampled_idx,
            "sampled_val_idx": sampled_val_idx,
            "args": vars(args),
            "timing_info": timing_info,
        }
        os.makedirs(os.path.dirname(shapley_path), exist_ok=True)
        with open(shapley_path, "wb") as f:
            pickle.dump(result, f)
        print(f"[info] saved Shapley to {shapley_path}")

    dv_result = np.array(dv_result)
    print("dv_result shape:", dv_result.shape)

    # ===== 5) Shapley value 정렬 =====
    # dv_result: (num_train_dp, 2, val_sample_num)
    acc_contrib = dv_result[:, 1, :]            # (num_train_dp, val_sample_num)
    acc_sum_per_train = acc_contrib.sum(axis=1) # (num_train_dp,)

    # 낮은 Shapley부터 inspect하기 위해 오름차순 정렬
    sorted_indices_ascending = np.argsort(acc_sum_per_train)  # 작은 값이 앞

    # ===== 6) Poison indices 재현 & 매칭 =====
    poison_indices_global, full_train_size, num_flipped = get_poison_indices(
        dataset_name, poison_pct, poison_seed
    )
    
    # sampled_idx 중 실제로 poison된 것 식별
    # sampled_idx[i]는 전체 train set에서의 원래 index
    poisoned_mask = np.array([int(idx) in poison_indices_global for idx in sampled_idx])
    total_poisoned_in_sample = poisoned_mask.sum()
    
    print(f"\n[info] Poison info:")
    print(f"  full train set size: {full_train_size}")
    print(f"  total flipped in full set: {num_flipped} ({poison_pct}%)")
    print(f"  sampled train set size: {len(sampled_idx)}")
    print(f"  poisoned in sampled set: {total_poisoned_in_sample} "
          f"({total_poisoned_in_sample/len(sampled_idx)*100:.1f}%)")

    if total_poisoned_in_sample == 0:
        print("[WARNING] No poisoned data found in sampled set! Check indices.")
        return

    # ===== 7) Detection curve 계산 =====
    print(f"\n[info] Computing detection curves...")
    print(f"[info] Inspect percentages: {num_train_selected_list[0]}% ~ {num_train_selected_list[-1]}%")

    detection_results = []  # (inspect_pct, k_inspect, detected, detection_rate)

    for inspect_pct in num_train_selected_list:
        k_inspect = int(num_train_dp * inspect_pct / 100)
        k_inspect = min(k_inspect, len(sorted_indices_ascending))
        if k_inspect <= 0:
            continue
        
        inspected = sorted_indices_ascending[:k_inspect]
        detected = poisoned_mask[inspected].sum()
        detection_rate = detected / total_poisoned_in_sample
        
        detection_results.append({
            'inspect_pct': inspect_pct,
            'k_inspect': k_inspect,
            'detected': int(detected),
            'total_poisoned': int(total_poisoned_in_sample),
            'detection_rate': float(detection_rate),
        })

    # Random baseline: expected detection rate = inspect_pct / 100
    random_detection = []
    for inspect_pct in num_train_selected_list:
        k_inspect = int(num_train_dp * inspect_pct / 100)
        k_inspect = min(k_inspect, len(sorted_indices_ascending))
        if k_inspect <= 0:
            continue
        expected_rate = k_inspect / len(sampled_idx)
        random_detection.append({
            'inspect_pct': inspect_pct,
            'detection_rate': float(expected_rate),
        })

    # ===== 8) 결과 출력 =====
    print("\n" + "="*80)
    print("WRONG LABEL DETECTION RESULTS")
    print("="*80 + "\n")

    detection_rates = [r['detection_rate'] for r in detection_results]
    random_rates = [r['detection_rate'] for r in random_detection]
    inspect_pcts = [r['inspect_pct'] for r in detection_results]

    print(f"poison: {poison_pct}%")
    print(f"poisoned in sampled set: {total_poisoned_in_sample}/{len(sampled_idx)}")
    print(f"\ndetection rates (lowest Shapley first):")
    print(f"{[int(round(r * 10000)) for r in detection_rates]}")
    print(f"\nrandom baseline:")
    print(f"{[int(round(r * 10000)) for r in random_rates]}")
    print(f"\ninspect percentages:")
    print(f"{inspect_pcts}")

    print("\n" + "="*80)

    # ===== 9) 결과 저장 (txt) =====
    def add_early_stopping_info(f, es_base_path, method_dir, shapley_path, log_early_stopping):
        if not log_early_stopping:
            return
        
        setting_name = os.path.basename(shapley_path).replace('.pkl', '')
        early_stop_dir = f"{es_base_path}/shapley/{method_dir}/early_stopping"
        early_stop_path = f"{early_stop_dir}/{setting_name}.txt"
        
        if not os.path.exists(early_stop_path):
            return
        
        with open(early_stop_path, 'r') as es_f:
            lines = es_f.readlines()
        
        # Find data lines (skip header and statistics)
        data_lines = []
        for line in lines:
            stripped = line.strip()
            if not stripped:
                continue
            if any(stripped.startswith(x) for x in ['TMC', '=', 'Dataset:', 'Mode:', 'Early stopping',
                                                      'Iter', '----', 'Statistics:', 'Total', 'Overall',
                                                      'Early stop', 'Early Stopping Distribution', 'Poison']):
                continue
            if stripped.startswith('- '):
                continue
            parts = stripped.split()
            if '█' in stripped and not (len(parts) >= 5 and parts[0].isdigit()):
                continue
            if len(parts) >= 5 and parts[0].isdigit() and '/' in parts[2]:
                data_lines.append(stripped)
        
        if not data_lines:
            return
        
        early_stopped_count = sum(1 for line in data_lines if 'Early Stop' in line)
        completed_count = sum(1 for line in data_lines if 'Complete' in line)
        total_count = len(data_lines)
        
        percentages = []
        iter_stop_points = []
        
        for line in data_lines:
            parts = line.split()
            if len(parts) >= 5:
                iter_num = int(parts[0])
                pct_str = parts[4].rstrip('%')
                pct = float(pct_str)
                percentages.append(pct)
                iter_stop_points.append((iter_num, pct))
        
        f.write(f"\n")
        f.write(f"early stopping statistics:\n")
        f.write(f"total iterations: {total_count}\n")
        f.write(f"early stopped: {early_stopped_count} ({early_stopped_count/total_count*100:.1f}%)\n")
        f.write(f"completed: {completed_count} ({completed_count/total_count*100:.1f}%)\n")
        
        if percentages:
            avg_pct = np.mean(percentages)
            f.write(f"average early stop: {avg_pct:.2f}%\n")
        
        f.write(f"\n")
        f.write(f"distribution by percentage range:\n")
        bins = [(i, i+10) for i in range(0, 100, 10)]
        bin_counts = [0] * len(bins)
        
        for pct in percentages:
            bin_idx = min(int(pct // 10), 9)
            bin_counts[bin_idx] += 1
        
        max_count = max(bin_counts) if bin_counts else 1
        bar_width = 40
        
        for i, (start, end) in enumerate(bins):
            count = bin_counts[i]
            pct_of_total = (count / total_count * 100) if total_count > 0 else 0
            bar_length = int((count / max_count) * bar_width) if max_count > 0 else 0
            bar = '█' * bar_length
            f.write(f"{start:3d}-{end:3d}%: {count:4d} ({pct_of_total:5.1f}%) {bar}\n")
        
        f.write(f"\n")
        f.write(f"iteration early stop points (%):\n")
        max_iter = max(iter_num for iter_num, _ in iter_stop_points) if iter_stop_points else 0
        iter_width = len(str(max_iter))
        
        for iter_num, pct in iter_stop_points:
            f.write(f"{iter_num:{iter_width}d}: {pct:5.1f}%\n")

    shapley_filename = os.path.basename(shapley_path).replace('.pkl', '')
    predictions_filename = f"{shapley_filename}_detection.txt"
    predictions_txt_path = f"{detection_base_path}/shapley/{method_dir}/predictions/{predictions_filename}"
    os.makedirs(os.path.dirname(predictions_txt_path), exist_ok=True)

    with open(predictions_txt_path, 'a') as f:
        f.write(f"\n{'='*80}\n")
        f.write(f"dataset: {dataset_name}\n")
        f.write(f"train: {num_train_dp}, val: {val_sample_num}\n")
        f.write(f"seed: {seed}\n")
        f.write(f"poison: {poison_pct}% (seed={poison_seed})\n")
        f.write(f"poisoned in sampled set: {total_poisoned_in_sample}/{len(sampled_idx)} "
                f"({total_poisoned_in_sample/len(sampled_idx)*100:.1f}%)\n")
        f.write(f"\n")

        if approximate == "eigen":
            f.write(f"eigen rank: {eigen_rank_pct}% (actual: {eigen_rank})\n")
            f.write(f"solver: {eigen_solver}, dtype: {eigen_dtype}\n")
            f.write(f"eigen mode lambda={eigen_lambda_:.0e}\n")
        else:
            f.write(f"inv mode lambda={inv_lambda_:.0e}\n")

        f.write(f"\n")
        f.write(f"inspect percentages:\n")
        f.write(f"{inspect_pcts}\n")
        f.write(f"\ndetection rates (x10000, lowest Shapley first):\n")
        f.write(f"{[int(round(r * 10000)) for r in detection_rates]}\n")
        f.write(f"\nrandom baseline (x10000):\n")
        f.write(f"{[int(round(r * 10000)) for r in random_rates]}\n")

        # Add early stopping statistics if flag is enabled
        add_early_stopping_info(f, detection_base_path, method_dir, shapley_path, log_early_stopping)

    print(f"[info] saved detection results to {predictions_txt_path}")

    # ===== 10) 결과 저장 (pkl) =====
    pkl_filename = f"{shapley_filename}_detection.pkl"
    pkl_path = f"{detection_base_path}/shapley/{method_dir}/predictions/{pkl_filename}"

    detection_bundle = {
        "args": vars(args),
        "dataset_name": dataset_name,
        "seed": seed,
        "num_train_dp": num_train_dp,
        "val_sample_num": val_sample_num,
        "approximate": approximate,
        "poison_pct": poison_pct,
        "poison_seed": poison_seed,
        "total_poisoned_in_sample": int(total_poisoned_in_sample),
        "sampled_idx": sampled_idx,
        "poisoned_mask": poisoned_mask,
        "shapley_values": acc_sum_per_train,
        "sorted_indices_ascending": sorted_indices_ascending,
        "detection_results": detection_results,
        "random_detection": random_detection,
        "timing_info": timing_info,
    }

    with open(pkl_path, "wb") as f:
        pickle.dump(detection_bundle, f)
    print(f"[info] saved detection pkl to {pkl_path}")

    # ===== Print timing summary =====
    if timing_info:
        print("\n" + "="*80)
        print("TIMING SUMMARY")
        print("="*80)
        
        if 'gpu_info' in timing_info:
            gpu_info = timing_info['gpu_info']
            print("\nGPU Information:")
            print("-" * 40)
            for key, value in gpu_info.items():
                print(f"{key:.<40} {value}")
            print("-" * 40 + "\n")
        
        print("Timing Measurements:")
        print("-" * 40)
        for key, value in timing_info.items():
            if key != 'gpu_info':
                print(f"{key:.<40} {value:.4f}s")
        print("="*80 + "\n")


if __name__ == "__main__":
    main()
